name: Build LaTeX document (WaterlooWorks)

on:
  push:
    tags:
      - "v**-waterlooworks"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          post_compile: |
            mv 'main.pdf' 'Resume_Mohan_Dong_WaterlooWorks.pdf'

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Resume (WaterlooWorks)
          path: Resume_Mohan_Dong_WaterlooWorks.pdf

      - name: Publish release
        run: |
          gh release create $GITHUB_REF_NAME "Resume_Mohan_Dong_WaterlooWorks.pdf" --title "Resume (WaterlooWorks)" --notes "Built on $(date)"
        env:
          GH_TOKEN: ${{ github.token }}
